server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: backend-app-clinica

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:app_clinica}?serverTimezone=UTC&sslmode=prefer
    username: ${DB_USER:jan}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      timeout: 5000 # Configuracion de tiempos (milisegundos) de conexion
      client-type: lettuce  # Opcional: especificar si usas lettuce o jedis
      lettuce:
        client-name: my-redis-client  # Opcional si solo quieres darle nombre a tu cliente
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  ai:
#    anthropic:
#      api-key: ${ANTHROPIC_API_KEY:}

    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

      # Configuracion de embeddings
      embedding:
        options:
          model: text-embedding-3-small

    # Configuracion de VectorStore
    vectorstore:
      pgvector:
        dimensions: 1536
        initialize-schema: true
        distance-type: cosine_distance
        index-type: hnsw

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:usuario}
    password: ${MAIL_PASSWORD:password}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            ssl:
              enable: false
    default-encoding: UTF-8

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.data.redis: DEBUG

# Configuracion del servidor FHIR
fhir:
  server:
    url: ${FHIR_SERVER_URL:http://localhost:8080/fhir}
    token:

# Configuracion JWT
jwt:
  secret-key: ${JWT_SECRET_KEY:secret}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION_TIME:604800000} # 7 days

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  phone-from: ${TWILIO_PHONE_NUMBER:}
