server:
  port: 8081

spring:
  application:
    name: backend-app-clinica

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:app_clinica}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      timeout: 5000 # Configuración de tiempos (milisegundos) de conexión
      client-type: lettuce  # Opcional: especificar si usas lettuce o jedis
      lettuce:
        client-name: my-redis-client  # Opcional si solo quieres darle nombre a tu cliente
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
      ssl:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# Configuración del servidor FHIR
fhir:
  server:
    url: ${FHIR_SERVER_URL:http://localhost:8080/fhir}
    token:

# Configuración JWT
jwt:
  secret-key: ${SECRET_KEY}
  expiration: ${EXPIRATION_TIME}
